twig:
    file_name_pattern: '*.twig'
    paths:
        'src/Counterparty/InfrastructureCounterparty/ApiCounterparty/templatesCounterparty': 'counterparty'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesPartNumbers': 'partNumbers'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesOriginalRooms': 'originalRooms'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesReplacingOriginalNumbers': 'replacingOriginalNumbers'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesAccessoriesParts/PartName': 'partName'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesAccessoriesParts/CarBrands': '—ÅarBrands'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesAccessoriesParts/Sides': 'sides'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesAccessoriesParts/Bodies': 'bodies'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesAccessoriesParts/Axles': 'axles'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesAccessoriesParts/Availability': 'availability'
        'src/AutoPartsWarehouse/InfrastructureAutoPartsWarehouse/ApiAutoPartsWarehouse/templatesAutoPartsWarehouse': 'autoPartsWarehouse'
        'src/AutoPartsWarehouse/InfrastructureAutoPartsWarehouse/ApiAutoPartsWarehouse/templatesPaymentMethod': 'paymentMethod'
        'src/Sales/InfrastructureSales/ApiSales/templatesSales': 'sales'
        'src/Participant/InfrastructureParticipant/ApiParticipant/templatesParticipant': 'participant'
        'src/Main/InfrastructureMain/ApiMain/templatesMain': 'main'
when@test:
    twig:
        strict_variables: true
