twig:
    file_name_pattern: '*.twig'
    paths:
        'src/Counterparty/InfrastructureCounterparty/ApiCounterparty/templatesCounterparty': 'counterparty'
        'src/PartNumbers/InfrastructurePartNumbers/ApiPartNumbers/templatesPartNumbers': 'partNumbers'
        'src/AutoPartsWarehouse/InfrastructureAutoPartsWarehouse/ApiAutoPartsWarehouse/templatesAutoPartsWarehouse': 'autoPartsWarehouse'
        'src/Sales/InfrastructureSales/ApiSales/templatesSales': 'sales'
        'src/Participant/InfrastructureParticipant/ApiParticipant/templatesParticipant': 'registerAuthenticationParticipant'
        'src/Main/InfrastructureMain/ApiMain/templatesMain': 'main'
when@test:
    twig:
        strict_variables: true
