twig:
    file_name_pattern: '*.twig'
    paths:
        'src/Counterparty/InfrastructureCounterparty/ApiCounterparty/templatesCounterparty': 'counterparty'

when@test:
    twig:
        strict_variables: true
