services:
  php-fpm:
    container_name: php_fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - ./../:/var/www/

  nginx:
    container_name: nginX
    build:
      context: ./nginx
    ports:
      - 8888:80
    volumes:
      - ..:/var/www/:rw
    depends_on:
      - php-fpm

  mysql:
    container_name: mysqL
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=_TMP"
      - "MYSQL_USER=lm"
      - "MYSQL_PASSWORD=symfony"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  pma:
    container_name: pmA
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: lm
      PMA_PASSWORD: symfony
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql:
